# Generated by Django 5.0.6 on 2024-07-08 10:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChaiVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='chais/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('ML', 'Masala Chai'), ('GC', 'Ginger Chai'), ('CC', 'Cardamom Chai'), ('KC', 'Kashmiri Chai'), ('IC', 'Iced Chai'), ('OC', 'Other Chai')], default='ML', max_length=2)),
            ],
        ),
    ]
