# Generated by Django 5.0.6 on 2024-07-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_chaivariety_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaivariety',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='chaivariety',
            name='description',
            field=models.CharField(default='', max_length=400),
        ),
    ]
