# Generated by Django 5.0.6 on 2024-07-08 13:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_chaicertificate_chaireview_store'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='chais_varities',
            new_name='chai_varieties',
        ),
        migrations.RemoveField(
            model_name='chaicertificate',
            name='certificate',
        ),
        migrations.RemoveField(
            model_name='chaicertificate',
            name='date_issued',
        ),
        migrations.RemoveField(
            model_name='chaivariety',
            name='description',
        ),
        migrations.RemoveField(
            model_name='chaivariety',
            name='price',
        ),
        migrations.RemoveField(
            model_name='store',
            name='loction',
        ),
        migrations.AddField(
            model_name='chaicertificate',
            name='certificate_number',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='chaicertificate',
            name='issued_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='store',
            name='location',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='chaicertificate',
            name='chai',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='testapp.chaivariety'),
        ),
        migrations.AlterField(
            model_name='chaireview',
            name='chai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='testapp.chaivariety'),
        ),
        migrations.AlterField(
            model_name='chaireview',
            name='comment',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='chaireview',
            name='rating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='chaivariety',
            name='type',
            field=models.CharField(choices=[('ML', 'MASALA'), ('GR', 'GINGER'), ('KL', 'KIWI'), ('PL', 'PLAIN'), ('EL', 'ELAICHI')], default='ML', max_length=2),
        ),
    ]
